import { createClient } from "@/lib/supabase/server"
import { DataTable } from "@/dashboard/components/DataTable"
import { columns } from "./columns"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { AlertCircle } from "lucide-react"

export default async function SeoTasksPage() {
  const supabase = await createClient()
  
  const { data: tasks, error } = await supabase
    .from("seo_tasks")
    .select("*")
    .order("created_at", { ascending: false })

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-2">
        <h1 className="text-2xl font-bold tracking-tight">SEO Tasks</h1>
        <p className="text-[var(--muted-foreground)]">Review and manage technical/content SEO tasks generated by the engine.</p>
      </div>

      {error ? (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>
            Gagal mengambil data SEO Tasks. Pastikan tabel <code>seo_tasks</code> sudah ada.
          </AlertDescription>
        </Alert>
      ) : (
        <DataTable columns={columns} data={tasks || []} searchKey="title" />
      )}
    </div>
  )
}
